# yaml-language-server: $schema=https://raw.githubusercontent.com/nogahighland/active_record_mysql_repl/refs/heads/main/json_schemas/army_schema.json

database_config: ./.army.sample/databases.sample.yml
associations: ./.army.sample/associations.sample.yml
extensions_dir: ./.army.sample/extensions
pryrc: ./.army.sample/.pryrc.sample
